apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  namespace: ml-models
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-models
  template:
    metadata:
      labels:
        app: ml-models
    spec:
      containers:
      - name: ml-model-containers
        image: ml_model_app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001