apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
  namespace: ml-models
spec:
  type: LoadBalancer
  selector:
    app: ml-model
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 5001
  